"""add draft version table

Revision ID: 0007
Revises: 0006_add_video_name
Create Date: 2025-10-13 16:03:47.779795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006_add_video_name'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('script_version', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('draft_name', sa.String(length=255), nullable=True),
    sa.Column('resource', postgresql.ENUM(name='draft_resource', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'version', name='uq_draft_versions_draft_id_version')
    )
    op.create_index(op.f('ix_draft_versions_draft_id'), 'draft_versions', ['draft_id'], unique=False)
    # Add current_version column as nullable first
    op.add_column('drafts', sa.Column('current_version', sa.Integer(), nullable=True))
    # Set current_version to 1 for all existing rows
    op.execute("UPDATE drafts SET current_version = 1 WHERE current_version IS NULL")
    # Now make the column NOT NULL
    op.alter_column('drafts', 'current_version', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make current_version nullable and drop it
    op.alter_column('drafts', 'current_version', nullable=True)
    op.drop_column('drafts', 'current_version')
    op.drop_index(op.f('ix_draft_versions_draft_id'), table_name='draft_versions')
    op.drop_table('draft_versions')
    # ### end Alembic commands ###


