"""change video task status to enum

Revision ID: 0008
Revises: 0007
Create Date: 2025-10-16 17:17:30.971709

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    video_task_status = sa.Enum(
        "INITIALIZED", "PROCESSING", "COMPLETED", "FAILED", name="video_task_status"
    )
    video_task_status.create(op.get_bind(), checkfirst=True)
    # Add column with default value to avoid null constraint violation
    op.add_column(
        "video_tasks",
        sa.Column(
            "render_status",
            video_task_status,
            nullable=False,
            default="COMPLETED",
            server_default="COMPLETED",
        ),
    )
    op.create_index(
        op.f("ix_video_tasks_render_status"),
        "video_tasks",
        ["render_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_video_tasks_render_status"), table_name="video_tasks")
    op.drop_column("video_tasks", "render_status")
    # ### end Alembic commands ###
