"""add video table and video_id to video_tasks

Revision ID: 0009
Revises: 0008
Create Date: 2025-10-31 00:00:00.000000

"""
import logging

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

logger = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Add PENDING status to the enum
    logger.info("Adding PENDING status to video_task_status enum")
    op.execute("ALTER TYPE video_task_status ADD VALUE IF NOT EXISTS 'PENDING' AFTER 'INITIALIZED'")

    # 2. Create videos table
    logger.info("Creating videos table")
    op.create_table(
        "videos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.String(length=255), nullable=False),
        sa.Column("draft_id", sa.String(length=255), nullable=False),
        sa.Column("video_name", sa.String(length=255), nullable=True),
        sa.Column("resolution", sa.String(length=64), nullable=True),
        sa.Column("framerate", sa.String(length=32), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("oss_url", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_videos_draft_id"), "videos", ["draft_id"], unique=False)
    op.create_index(op.f("ix_videos_video_id"), "videos", ["video_id"], unique=True)

    # 3. Add video_id column to video_tasks table
    logger.info("Adding video_id column to video_tasks table")
    op.add_column("video_tasks", sa.Column("video_id", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_video_tasks_video_id"), "video_tasks", ["video_id"], unique=False)

    # 4. Change progress column from Integer to Float for decimal precision
    logger.info("Changing progress column from Integer to Float")
    # First, alter the column type
    op.alter_column(
        "video_tasks",
        "progress",
        type_=sa.Float(),
        existing_type=sa.Integer(),
        existing_nullable=True,
    )

    logger.info("Migration 0009 completed successfully")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Change progress column back from Float to Integer
    logger.info("Reverting progress column from Float to Integer")
    op.alter_column(
        "video_tasks",
        "progress",
        type_=sa.Integer(),
        existing_type=sa.Float(),
        existing_nullable=True,
    )

    # 2. Drop video_id column from video_tasks
    logger.info("Dropping video_id column from video_tasks")
    op.drop_index(op.f("ix_video_tasks_video_id"), table_name="video_tasks")
    op.drop_column("video_tasks", "video_id")

    # 3. Drop videos table
    logger.info("Dropping videos table")
    op.drop_index(op.f("ix_videos_video_id"), table_name="videos")
    op.drop_index(op.f("ix_videos_draft_id"), table_name="videos")
    op.drop_table("videos")

    # Note: Cannot remove PENDING enum value as PostgreSQL doesn't support removing enum values
    # To fully downgrade, you would need to recreate the enum without PENDING
    logger.warning("PENDING status in video_task_status enum cannot be automatically removed")

    logger.info("Migration 0009 downgrade completed")
    # ### end Alembic commands ###

