"""remove draft_url from video_tasks

Revision ID: 0010
Revises: 0009
Create Date: 2025-01-01 00:00:00.000000

"""

import logging

import sqlalchemy as sa

from alembic import op

logger = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    logger.info("Removing draft_url column from video_tasks table")
    op.drop_column("video_tasks", "draft_url")
    logger.info("Migration 0010 completed successfully")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    logger.info("Restoring draft_url column to video_tasks table")
    op.add_column("video_tasks", sa.Column("draft_url", sa.Text(), nullable=True))
    logger.info("Migration 0010 downgrade completed")
    # ### end Alembic commands ###
