"""add draft_archive table

Revision ID: 0011
Revises: 0010
Create Date: 2025-01-15 00:00:00.000000

"""

import logging
import uuid

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

from alembic import op

logger = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision = "0011"
down_revision = "0010"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    logger.info("Creating draft_archives table")
    op.create_table(
        "draft_archives",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "archive_id",
            UUID(as_uuid=True),
            nullable=False,
            default=uuid.uuid4,
        ),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("user_name", sa.String(length=255), nullable=True),
        sa.Column("draft_id", sa.String(length=255), nullable=False),
        sa.Column("draft_version", sa.Integer(), nullable=True),
        sa.Column("download_url", sa.Text(), nullable=True),
        sa.Column("total_files", sa.Integer(), nullable=True),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("downloaded_files", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "draft_id",
            "draft_version",
            name="uq_draft_archives_draft_id_version",
        ),
    )

    # Create indexes
    logger.info("Creating indexes on draft_archives table")
    op.create_index(
        op.f("ix_draft_archives_archive_id"),
        "draft_archives",
        ["archive_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_draft_archives_draft_id"),
        "draft_archives",
        ["draft_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_draft_archives_user_id"),
        "draft_archives",
        ["user_id"],
        unique=False,
    )

    logger.info("Migration 0011 completed successfully")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    logger.info("Dropping draft_archives table")
    op.drop_index(op.f("ix_draft_archives_user_id"), table_name="draft_archives")
    op.drop_index(op.f("ix_draft_archives_draft_id"), table_name="draft_archives")
    op.drop_index(op.f("ix_draft_archives_archive_id"), table_name="draft_archives")
    op.drop_table("draft_archives")
    logger.info("Migration 0011 downgrade completed")
    # ### end Alembic commands ###
