"""add archive_name column to draft_archive table

Revision ID: 0012
Revises: 0011
Create Date: 2025-01-15 00:00:00.000000

"""

import logging

import sqlalchemy as sa

from alembic import op

logger = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision = "0012"
down_revision = "0011"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    logger.info("Adding archive_name column to draft_archives table")
    op.add_column(
        "draft_archives",
        sa.Column("archive_name", sa.String(length=255), nullable=True),
    )
    logger.info("Migration 0012 completed successfully")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    logger.info("Dropping archive_name column from draft_archives table")
    op.drop_column("draft_archives", "archive_name")
    logger.info("Migration 0012 downgrade completed")
    # ### end Alembic commands ###
